### ISSUE TITLE
UnsatisfiableError

### ISSUE THREAD

**Issue by JunxiFeng** [pinellolab/simba#17]
Hello,

When I tried to download simba on MacOS, I encountered this error 
![Screen Shot 2023-07-20 at 10 50 15 PM](https://github.com/pinellolab/simba/assets/60299660/64cc9026-74c1-478b-9cf3-77a8b5b90bc4)

And I was sure how to fix it... Thank you so much!!

Best,
Junxi

**Comment by huidongchen** [comment]
> Hello,
> 
> When I tried to download simba on MacOS, I encountered this error ![Screen Shot 2023-07-20 at 10 50 15 PM](https://user-images.githubusercontent.com/60299660/254921249-64cc9026-74c1-478b-9cf3-77a8b5b90bc4.png)
> 
> And I was sure how to fix it... Thank you so much!!
> 
> Best, Junxi

Are you attempting to install 'simba' within the existing environment or a fresh one? It is highly recommended to install 'simba' in a newly created environment as follows:

```bash
conda create -n env_simba simba
conda activate env_simba
```

**Comment by JunxiFeng** [comment]
Thank you so much!
