### ISSUE TITLE
significance calculation

### ISSUE THREAD

**Issue by sinihak** [pinellolab/simba#18]
Hello,

I am giving a try to the significance calculation and facing some issues.

I am in a situation where I need to run the graph generation and the training separately, but cannot figure out, how I should save and read back the graph information for both the graph and graph_with_sig. What would be the correct way?

Also, does SIMBA have GPU support?

Best,
Sini

**Comment by jykr** [comment]
Hi Sini,

SIMBA outputs the directory your graph is saved in the output of `si.tl.gen_graph` ex) `Writing graph file "pbg_graph.txt" to "result_multiome_shareseq_v5/pbg/graph_5"` in cell 21 of [tutorial](https://github.com/pinellolab/simba_tutorials/blob/main/v1.1sig/multiome_shareseq_data_from_authors.ipynb).

You can load specific graph by specifying the directory as below and between cell 26-27 in the [tutorial](https://github.com/pinellolab/simba_tutorials/blob/main/v1.1sig/multiome_shareseq_data_from_authors.ipynb):
```
# load in graph ('graph0') info
si.load_graph_stats(path='./result_multiome_shareseq/pbg/graph0/')
# load in model info for ('graph0')
si.load_pbg_config(path='./result_multiome_shareseq/pbg/graph0/model/')
```

SIMBA does support GPU usage, and you can set `num_gpu` as 1 in model config as below:
```
# modify parameters
dict_config = si.settings.pbg_params.copy()
dict_config["num_gpus"] = 1
# change other parameters
# ...

## start training
si.tl.pbg_train(pbg_params = dict_config, auto_wd=True, save_wd=True, output='model')
```

Best,
Jayoung

**Comment by sinkahak** [comment]
Great, thanks! I read the tutorial but for some reason the function wasn't able to fetch the _with_sig model so I thought I understood something incorrectly. I found another roundabout for that, which works fine and but I will also try the original solution again. 

Best, Sini

**Comment by sinihak** [comment]
Great, thanks! I read the tutorial but for some reason the function wasn't able to fetch the _with_sig model so I thought I understood something incorrectly. I found another roundabout for that, which works fine and but I will also try the original solution again. 

Best, Sini

**Comment by lucapinello** [comment]
Thanks! Do you mind to share your work around? So we can consider updating
the docs.

**Comment by sinihak** [comment]
I saved both the graph params (si.settings.pbg_params) and the stats (si.settings.graph_stats) as json files. I noticed, that the graph stats obtained from si.settings.graph_stats is actually different from the graph_stats.json that are saved automatically to /pbg/graph/ and /pbg/graph_with_sig/ so I suppose that was causing the issues. Not sure if this is the expected behavior.
