### ISSUE TITLE
Error installing dev version

### ISSUE THREAD

**Issue by jesswhitts** [pinellolab/simba#29]
Hello,

I am trying to install the dev version, following the instructions on the readme, but get this error:

remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/pinellolab/simba_pbg/'

I can't even find the repo for simba_pbg to clone and install via pip, any suggestions on a fix?

Best,
Jess

**Comment by jykr** [comment]
Hi, could you try this again now?

**Comment by jesswhitts** [comment]
It works fine now, thank you!
